name: Deploy to Server

on:
  push:
    branches:
      - master  # или другая ветка

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add SSH key to agent
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 91.194.251.241 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd domains/tango-calendar.com/public_html
            git reset --hard
            git pull origin master
            /usr/local/php/php82/bin/php /usr/local/bin/composer install --no-dev --optimize-autoloader
            /usr/local/php/php82/bin/php /usr/local/bin/php artisan migrate --force
            /usr/local/php/php82/bin/php /usr/local/bin/php artisan cache:clear
            /usr/local/php/php82/bin/php /usr/local/bin/php artisan config:clear
            /usr/local/php/php82/bin/php /usr/local/bin/php artisan queue:restart

